version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "patientscheckout"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1qjj1x4zz5kw2"
s3_prefix = "patientscheckout"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
